### ISSUE TITLE
No README.md

### ISSUE THREAD

**Issue by fff** [abruzzi/tech-radar#1]
How to run it?
CHA PING.

**Comment by abruzzi** [comment]
Sorry for the inconvenient, I forgot to make a bower configuration, already fixed.

You can run it by simply run the following command:

``` sh
$ bower install
$ python -m SimpleHTTPServer 9999
```

and then open `http://localhost:9999` in browser.

**Comment by fff** [comment]
Nice!

From mobile device

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.45&pv=5.0.2]

On Wed, Jul 15, 2015 at 9:15 AM, Qiu Juntao < notifications@github.com [notifications@github.com] > wrote:
Sorry for the inconvenient, I forgot to make a bower configuration, already
fixed.

You can run it by simply run the following command:

$ bower install
$ python -m SimpleHTTPServer 9999

and then open http://localhost:9999 in browser.

—
Reply to this email directly or view it on GitHub
[https://github.com/abruzzi/tech-radar/issues/1#issuecomment-121512375] .[https://github.com/notifications/beacon/AAA3YUfcaeaE2iP0K3yPhAho0weH6MVnks5odf_9gaJpZM4FY1GH.gif]
